### ISSUE TITLE
data table with where confition

### ISSUE THREAD

**Issue by markyie** [nurisakbar/Garuda-CRUD-Generator#3]
trima kasih gan dgn Garuda-CRUD-Generator nya. Saya dari dulu follow pak nuris. pernah beli online video untuk pemula CI dari bapak.
Cuma sekarang saya stuck untuk dapatkan solusi gimana mau letakkan where clause di datatables. sudah habis googling masih belum bisa ketemu solusi terbaik.
Saya ada coba gunakan $this->db->where, sukses tapi pagination nya gak hilang. mohon bantuan.
Jazakallah.

**Comment by markyie** [comment]
sudah berhasil gan.. cuma masalah typo.. :D

**Comment by Mijoro603** [comment]
Allright

2018-07-10 15:31 GMT+03:00 markyie <notifications@github.com>:
